name: Talend CI

on:
  workflow_dispatch:
    inputs:
      BUILD_GOAL:
        description: Build Goal
        required: true
        default: test
        type: choice
        options:
        - test
        - package
        - install
        - deploy
      ITEM_FILTER:
        description: Item Filter
        required: false
        type: string
      ADDITIONAL_MVN_ARGS:
        description: Additional Maven Settings
        required: false
        type: string

jobs:
  build:
    uses: TalendPS/CICD_REF/.github/workflows/talend-ci.yml@master
    with:
      BUILD_GOAL: ${{ inputs.BUILD_GOAL }}
      ITEM_FILTER:  ${{ inputs.ITEM_FILTER }}
      ADDITIONAL_MVN_ARGS:  ${{ inputs.ADDITIONAL_MVN_ARGS }}
    secrets:
      GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
      # TALEND_CLOUD_TOKEN: ${{ secrets.TALEND_CLOUD_TOKEN }}
