name: Talend Commandline Installer

on:
  schedule:
    - cron: '17 5 * * 0' # every sunday at 5.17am

  workflow_dispatch:
    inputs:
      CLEAN_COMMANDLINE:
        description: 'Reinstall Commandline. Purge old installation if any.'
        required: false
        type: boolean
      TALEND_STUDIO_VERSION:
        description: 'Studio Patch Level'
        default: ${{ vars.TALEND_STUDIO_VERSION }}
        required: false
        type: string
      TALEND_STUDIO_BASE_URL:
        description: 'URL to get Studio base files'
        default: https://update.talend.com/Studio/8/base
        required: false
        type: string
      TALEND_STUDIO_UPDATE_URL:
        description: 'URL to get Studio update files'
        default: https://update.talend.com/Studio/8/updates
        required: false
        type: string

jobs:
  install:
    uses: TalendPS/CICD_REF/.github/workflows/talend-comandline-installer.yml@master
    with:
      CLEAN_COMMANDLINE: ${{ github.event.schedule && true || inputs.CLEAN_COMMANDLINE }}
      TALEND_STUDIO_VERSION:  ${{ inputs.TALEND_STUDIO_VERSION }}
      TALEND_STUDIO_BASE_URL:  ${{ github.event.schedule && (vars.TALEND_STUDIO_BASE_URL || 'https://update.talend.com/Studio/8/base') || inputs.TALEND_STUDIO_BASE_URL }}
      TALEND_STUDIO_UPDATE_URL:  ${{ github.event.schedule && (vars.TALEND_STUDIO_UPDATE_URL || 'https://update.talend.com/Studio/8/updates') || inputs.TALEND_STUDIO_UPDATE_URL }}
    secrets:
      GIT_TOKEN: ${{ secrets.GIT_TOKEN }}